<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>GrpcService</AssemblyName>
    <RootNamespace>IoTFarmBench.GrpcService</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.66.0" />
    <PackageReference Include="Grpc.AspNetCore.Server.Reflection" Version="2.66.0" />
    <PackageReference Include="Npgsql" Version="8.0.5" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="Protos\status.proto" GrpcServices="Server" />
    <Protobuf Include="Protos\farm_benchmark.proto" GrpcServices="Server" />
  </ItemGroup>
</Project>
